Feature/23
9in-team/iOS pull request #26
Opened 2023-04-06 14:29 UTC by cho1490

내 지원서 화면 Alert (문의, 추가 제출) 구현

현재 선택 된 뷰의 좌표를 구해오는 LocationViewWrapper 구현

2023-04-07 14:15 UTC, heonha requested changes
첫 리뷰라 이렇게 하는 것이 맞는지 모르겠네요 ㅎㅎ
사소한 부분이지만, 제 생각 공유 드려보았습니다~! 고생 많으셨습니다!

2023-04-07 14:15 UTC, heonha commented on 9in.team/9in.team/Presentation/Main/MyResume/MyResumeView.swift
> +                                                .frame(width: 30)
문의 버튼과 width가 다르므로 Image와 HStack의 frame alignment를 center로 줘서 
horizontal이 가운데로 정렬되면 깔끔하게 정렬 될 것 같은데 혹시 어떻게 생각하시나요?

2023-04-08 12:07 UTC, cho1490 commented on 9in.team/9in.team/Presentation/Main/MyResume/MyResumeView.swift
> +                                                .frame(width: 30)
개발할 때 깜빡하고 좌측 정렬로 생각하고 개발했네요 실수했습니다 ㅠ 
심지어 82번, 108번 라인의 alignment 값은 어떤 값을 넣어도 똑같은 결과가 나왔을텐데 제가 놓친 부분이네요!!

피그마 다시 확인하고 가운데 정렬인걸 지금 확인했습니다 ㅠㅠ alignment: .leading 코드 지웠습니다!

2023-04-08 12:08 UTC, cho1490 commented on 9in.team/9in.team/CustomView/LocationViewWrapper.swift
> +        }
맞습니다 ㅎㅎ
테스트 이후 코드를 삭제하지 않았네요 지우겠습니다 !

2023-04-09 04:00 UTC, heonha approved these changes

2023-04-09 04:03 UTC, merged

2023-04-09 04:07 UTC, heonha commented
고생 많으셨습니다! 🙌