Feature/54 카카오 로그인 토큰 암호화
9in-team/iOS pull request #60
Opened 2023-06-28 12:40 UTC by heonha

Keychain Service를 통해서 기존 UserDefault로 저장했던 로그인 토큰을 암호화하여 저장할 수 있도록 구현했습니다.
테스트 및 에러핸들링에 시간이 꽤 걸려서 Error 세분화 작업 및  Keychain, login 테스트 코드 작성했습니다.

close #54

2023-07-05 02:34 UTC, heonha commented
Kakao Talk 로그인에 문제가 있어 파악중입니다.
Kakao Web Login은 이상없습니다.
추후 이슈 만들어서 작업하도록 하겠습니다.

2023-07-05 13:12 UTC, cho1490 reviewed
코드 완전 아름다워요 ㅎㅎㅎ 많이 배우고 있습니다!

2023-07-05 13:12 UTC, cho1490 commented on NineInTeam/NineInTeam/Presentation/Membership/Service/Kakao/KakaoAuthService.swift
requestSignInSession (81번 라인) 메소드에 대한 질문이 있습니다!
requestSession  (89번 라인)
loginError (95번 라인)

requestSession 이 혹시 네트워크 지연에 따라 작업이 늦게 끝나는 상황이라고 가정하면
loginError 의 값이 항상 nil 일수도 있다고 생각합니다! 어떻게 생각하시나요!!

2023-07-08 10:04 UTC, heonha commented on NineInTeam/NineInTeam/Presentation/Membership/Service/Kakao/KakaoAuthService.swift
명확한 포인트 감사합니다!!
5초정도 딜레이 주고 이후 에러가 발생하도록 테스트 해보니 
로그인 에러임에도 불구하고 실제로 로그인 된것 처럼 화면이 넘어가는 것을 확인했습니다.
이부분 해결 후 테스트 해보고 다시 PR드리겠습니다~!

2023-07-08 10:07 UTC, heonha commented on NineInTeam/NineInTeam/Presentation/Membership/Service/Kakao/KakaoAuthService.swift
추가로 weak self 미사용하는 대신 로그인 버튼 2회 이상 누를 시에 대비해서 
로그인 전 cancellables 을 비우도록 수정,
Keychain 업데이트에 문제가 있어서 이부분도 수정하고 PR드리겠습니다!

2023-07-15 12:18 UTC, heonha commented
비동기 핸들링이 쉽지않군요
작업하면서 많이 배웠습니다 ㅎㅎㅎ

2023-07-17 12:10 UTC, cho1490 requested changes
가독성 향상을 위해 신경쓰신게 엄청 느껴지네요!!! 좋은 코드라고 생각이 듭니다!

2023-07-17 12:10 UTC, cho1490 commented on NineInTeam/NineInTeam/Presentation/Membership/SignIn/SignInView.swift
> +    @State var loginTask: Task<(), Error>?
사용하는 부분을 못찾았는데 혹시 사용할 변수인가요!?

2023-07-17 13:17 UTC, heonha commented on NineInTeam/NineInTeam/Presentation/Membership/SignIn/SignInView.swift
> +    @State var loginTask: Task<(), Error>?
앗 concurrency 사용하려다 원복했는데 잔재가 남았군요..! 수정후 커밋하겠습니다~!

2023-07-17 13:24 UTC, heonha commented
코드리뷰 반영후 커밋하였습니다!

2023-07-17 13:26 UTC, cho1490 approved these changes
고생하셨습니다! 짱~

2023-07-17 13:28 UTC, merged

2023-08-13 07:42 UTC, heonha commented
#53 의 보완작업