Feature/15 지원하기 화면 구성
9in-team/iOS pull request #64
Opened 2023-08-01 12:18 UTC by cho1490

- SubmitResumeView 지원하기 화면 구성
- DocumentPicker 생성하면서 PhotoPicker의 파일 위치 변경 (Util/Feature)

close #15

2023-08-10 11:52 UTC, heonha requested changes
죄송합니다 리뷰가 많이 늦었습니다. 
확인 한번 부탁드리겠습니다~

2023-08-10 11:52 UTC, heonha commented on NineInTeam/NineInTeam/Util/Feature/DocumentPicker.swift
> +        }
firstFileURL 으로 접근하면 정상,
outputFileURL로 접근하면 경로 오류가 뜨는 것으로 확인했습니다.

경로는 아래와 같이 확인했습니다.
firstFileURL: 앱샌드박스 경로/tmp/com.csh.9in-team-Inbox/this_is_test.pdf  (externalFileURL과 동일)
outputFileURL: 앱샌드박스 경로/tmp/this_is_test.pdf 

혹시 별도의 경로로 변경하는 이유가 있으신지 공유주시면 도움 될 것 같습니다!

2023-08-10 11:52 UTC, heonha commented on NineInTeam/NineInTeam/Presentation/Main/Home/SubmitResume/SubmitResumeViewModel.swift
> +        uploadPDF() { url, error in
()은 불필요한 것 같아 제거해도 좋을 것 같은데 혹시 어떻게 생각하시나요?

2023-08-17 13:40 UTC, cho1490 commented on NineInTeam/NineInTeam/Repository/Firebase/FirebaseStorageManager.swift
> +    static let kResumePDF = "ResumePDF"
현재는 많이 안쓰는거 같구용 objc 에서 많이 사용했다고 들었던거 같네요
저는 k가 멋있어 보여서 적용한 프로젝트가 있습니다~

2023-08-17 13:41 UTC, cho1490 commented on NineInTeam/NineInTeam/Util/Feature/DocumentPicker.swift
> +        }
해당 문제의 원인과 해결방안을 아직 찾지 못해서요! 이 부분은 금방 찾아내서 고쳐보겠습니다.

2023-08-17 13:46 UTC, cho1490 commented on NineInTeam/NineInTeam/Util/Feature/DocumentPicker.swift
이미지를 선택할 때 사용하는 PhotoPicker 와 비슷한 형태로 구현해야겠다 생각해서 UIViewControllerRepresentable 을 채택했구용
지금 생각해보니 굳이 UIKit 을 컨버팅 하는것보단 그냥 SwiftUI 에서 제공하는 기능을 사용하는게 좋은거 같아서 fileImporter 로 수정 완료했습니다.

2023-08-17 13:47 UTC, cho1490 commented on NineInTeam/NineInTeam/Presentation/Main/Home/SubmitResume/SubmitResumeViewModel.swift
> +        uploadPDF() { url, error in
저도 불필요하다고 생각하며 수정했습니다.

2023-08-18 08:51 UTC, heonha commented on NineInTeam/NineInTeam/Repository/Firebase/FirebaseStorageManager.swift
> +    static let kResumePDF = "ResumePDF"
아 그래서 그런지 저도 k가 되게 익숙하더라구요 ㅎㅎ
확인 감사합니다 ㅎㅎ

2023-08-24 13:05 UTC, heonha requested changes
코드가 깔끔해서 항상 리뷰할 때 편안하네요 ㅎㅎ
한가지 부분만 검토 해주시면 merge해도 괜찮을 것 같습니다!

2023-08-24 13:06 UTC, heonha commented on NineInTeam/NineInTeam/Util/Feature/DocumentPicker.swift
> +        }
잘 작동하는 것 확인했습니다 ㅎㅎ

2023-08-31 12:37 UTC, cho1490 commented on NineInTeam/NineInTeam/Presentation/Main/Home/SubmitResume/SubmitResumeViewModel.swift
>              }
오호! 좋은 리뷰 감사합니다ㅎㅎ
access 를 요청한 메소드 내에서 해제까지 진행하고 싶어서 
각각의 url들이 역할을 다했을때 stop 하도록 수정했습니다!

2023-09-10 10:48 UTC, heonha approved these changes
테스트 완료했습니다.
수고하셨습니다! ㅎㅎ

2023-09-14 12:29 UTC, merged